services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./NginxLoadBalancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
      - server3

  server1:
    build:
      context: .
      dockerfile: NginxLoadBalancer/Dockerfile
    image: server1:latest
    environment:
      - PORT=5000
      - SERVER_ID=server1
    expose:
      - "5000"

  server2:
    build:
      context: .
      dockerfile: NginxLoadBalancer/Dockerfile
    image: server2:latest
    environment:
      - PORT=5001
      - SERVER_ID=server2
    expose:
      - "5001"

  server3:
    build:
      context: .
      dockerfile: NginxLoadBalancer/Dockerfile
    image: server3:latest
    environment:
      - PORT=5002
      - SERVER_ID=server3
    expose:
      - "5002"