services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - 5343:80
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - /data
    
  loadbalancer:
    image: loadbalancer
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./LoadBalancer/config.json:/app/config.json
    environment:
    - SEQ_URL=http://0.0.0.0:5343
    depends_on:
      - seq
      - server1
      - server2
      - server3

  server1:
    image: kennethreitz/httpbin:latest
    environment:
      - SERVER_ID=server1
    expose:
      - "5000:80"

  server2:
    image: kennethreitz/httpbin:latest
    environment:
      - SERVER_ID=server1
    expose:
      - "5001:80"

  server3:
    image: kennethreitz/httpbin:latest
    environment:
      - SERVER_ID=server1
    expose:
      - "5002:80"