services:
  loadbalancer:
    image: loadbalancer
    build:
      context: .
      dockerfile: LoadBalancer/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server1
      - server2
      - server3

  server1:
    image: server1
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - PORT=5000
      - SERVER_ID=server1
    expose:
      - "5000"

  server2:
    image: server2
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - PORT=5001
      - SERVER_ID=server2
    expose:
      - "5001"

  server3:
    image: server3
    build:
      context: .
      dockerfile: Server/Dockerfile
    environment:
      - PORT=5002
      - SERVER_ID=server3
    expose:
      - "5002"
